version: "2"
services:

  pki:
    image: pki
    build:
      context: pki
    working_dir: "/"
    environment:
      MONGODB_URL: "mongodb://mongo:27017"
    ports:
      - "127.0.0.1:5000:5000"

  mongo:
    image: "mongo:4.2"
    restart: "always"
    ports:
      - "127.0.0.1:27017:27017"
    volumes:
      - "mongo:/data"

  nginx:
    network_mode: "host"
    image: "nginx:1.19.1"
    volumes:
      - "./tests/nginx/nginx.conf:/etc/nginx/nginx.conf"
      - "./tests/nginx/ssl:/ssl"

  mongo-express:
    image: "mongo-express:0.54"
    restart: "always"
    environment:
      ME_CONFIG_MONGODB_SERVER: "mongo"
    ports:
      - "127.0.0.1:8081:8081"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"

  whoami:
    image: "containous/whoami"


volumes:
  mongo: